---
- name: Installer Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Demarrer et activer Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Publier la page web avec l'IP de la base de donnees
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ web_page_path }}"
    owner: root
    group: root
    mode: "0644"
